"""Canonical text rendering of the schema, injected into every model prompt.

Generated by introspecting the live database rather than hand-written, so the
description cannot drift from the actual schema.
"""

import re
import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).resolve().parents[1] / "data" / "db" / "mfg.db"
ASOF = "2026-06-30"

HEADER = f"""SQLite database: manufacturing operations.
Dates are TEXT: 'YYYY-MM-DD' for dates, 'YYYY-MM-DD HH:MM:SS' for timestamps.
Data covers the 12 months ending {ASOF}; treat {ASOF} as the current date.
Notation: PK marks a primary key, '-> table.col' marks a foreign key, and
name[a|b|c] means the column accepts only those values.

Tables:"""


def _enums(ddl):
    out = {}
    for col, vals in re.findall(r"CHECK\s*\(\s*(\w+)\s+IN\s*\(([^)]*)\)\s*\)", ddl):
        out[col] = [v.strip().strip("'") for v in vals.split(",")]
    return out


def schema_prompt(db_path=DB_PATH):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    tables = cur.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY rowid").fetchall()

    lines = []
    for table, ddl in tables:
        enums = _enums(ddl)
        fks = {f[3]: (f[2], f[4])
               for f in cur.execute(f"PRAGMA foreign_key_list({table})").fetchall()}
        parts = []
        for _, name, _, _, _, pk in cur.execute(f"PRAGMA table_info({table})").fetchall():
            frag = name
            if pk:
                frag += " PK"
            if name in enums:
                frag += "[" + "|".join(enums[name]) + "]"
            if name in fks:
                frag += f" -> {fks[name][0]}.{fks[name][1]}"
            parts.append(frag)
        lines.append(f"{table}({', '.join(parts)})")

    conn.close()
    return HEADER + "\n" + "\n".join(lines)


if __name__ == "__main__":
    text = schema_prompt()
    print(text)
    print()
    print(f"[{len(text)} chars, ~{len(text) // 4} tokens, "
          f"{len(text.splitlines()) - 7} tables]")
